<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\InvoiceEntity\InvoiceEntity.csproj" />
    <ProjectReference Include="..\TsvFileFinder\TsvFileFinder.csproj" />
    <ProjectReference Include="..\TsvLoader\TsvLoader.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
